### ISSUE TITLE
Bind fails for some kinds of const arguments

### ISSUE THREAD

**Issue by cdion** [kristianlm/chicken-bind#1]
I was trying to use chicken-bind with the gl3.h header that comes with the OpenGL framework on MacOS 10.8.3 and XCode when I ran into the following bug.

When chicken-bind parses the following function signature:

GLAPI void APIENTRY glMultiDrawElements (GLenum mode, const GLsizei _count, GLenum type, const GLvoid_ const *indices, GLsizei primcount);

it produces this error:

Error: bad argument list syntax: (const star (id "indices") comma (id "GLsizei") (id "primcount") close-paren)

Here is a simple example which demonstrates the error:

(use bind)
(import chicken scheme foreign)

(bind\* #<<EOF
  void this_works(const void **foo) {
  }
EOF
)

;(bind\* #<<EOF
;  void this_doesnt(const void\* const *foo) {
;  }
;EOF
;)

I can work around this behaviour by removing the second const from the signature, but it would be nice if chicken-bind supported this.  I'm not sure how to make the fix myself, as I've just started learning scheme.

**Comment by kristianlm** [comment]
Hi Chris, and sorry for the late reply.

This is a fork of the official repo, and I haven't worked with the parser, just the code generator, so I don't think I can be of much help.

Try posting to the chicken-users mailing list instead, that's where you'll find the official bind maintainer (Felix) and other helpful souls.
