### ISSUE TITLE
Not pushed to main?

### ISSUE THREAD

**Issue by dleslie** [kristianlm/chicken-bind#2]
I have bind 1.5.2 installed and I still get the instance-ref error exhibited by:

``` shell
    echo "class Foo {}; class Bar { public: void foo(Foo &foo); }; " | chicken-bind - -o -
```

**Comment by kristianlm** [comment]
Hi Dan,

Only some of these changes made it back upstream. The instance-ref did unfortunately not. [Your patch](http://lists.gnu.org/archive/html/chicken-users/2014-03/msg00108.html) should get applied by the bind maintainer soon!

**Comment by dleslie** [comment]
Hmm, so bind still doesn't support moving small structures around on the stack? Sad. :(
